name = "scope-registry"
main = "src/worker.ts"
compatibility_date = "2023-07-07"
node_compat = true

[build.upload]
type = "module"

[[d1_databases]]
binding = "DB"
database_name = "scope-labels"
database_id = "a1421537-18f6-4f34-8533-fbe588d6e0c3"
